#server.port=8081
spring.mongodb.host=localhost
spring.mongodb.port=27017
spring.mongodb.database=shara
server.port=8081
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
#spring.security.oauth2.resourceserver.jwt.issuer-uri=https://dev-5vgjnzmflot865hn.us.auth0.com/oauth2/default
#spring.security.oauth2.resourceserver.jwt.audience=api://default

spring.security.oauth2.resourceserver.jwt.issuer-uri=https://dev-5vgjnzmflot865hn.us.auth0.com/
spring.security.oauth2.resourceserver.jwt.audience=https://customerapi.example.com

spring.main.allow-bean-definition-overriding=true




